### ISSUE TITLE
Incompatible Version of DIV2007 required

### ISSUE THREAD

**Issue by simare** [franzholz/transactor#4]
Hello, 
when trying to install tt-products with transactor and transactor-paypal on TYPO3 12 with PHP 8.2 I run into the following issue.

`Fatal error: Declaration of JambageCom\Div2007\Base\StatusProviderBase::getStatus() must be compatible with TYPO3\CMS\Reports\StatusProviderInterface::getStatus(): array in /var/www/html/vendor/jambagecom/div2007/Classes/Base/StatusProviderBase.php on line 67`

Upon checking the dependencies I notice that in the require version of div2007 the return type is not part of the signatur
https://github.com/franzholz/div2007/blob/0cc461ad0ec5f537ebe3a9391ae0a097447429bb/Classes/Base/StatusProviderBase.php#L67

With the current master it is correct https://github.com/franzholz/div2007/blob/95b22175bb51e320530f3471f4acce34c4562ba0/Classes/Base/StatusProviderBase.php#L70

So currently it is not possible to install the transactor for me. 
I don't know how much changed between versions of div2007 but maybe it is possible to create new versions and update the constraints?

Best
Ramon

**Comment by franzholz** [comment]
I have now prepared a transactor_paypal 0.6.0 on the develop branch. Test this one.
